[package]
name = "test-notcurses"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notcurses = "3.5.0"
sixel-bytes = "0.2.3"
