[package]
name = "notrogue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notcurses = "3.5.0"
lazy_static = "1.4.0"
legion = "0.4.0"
log = "0.4"
